
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vishnu Nair
 */
public class Converter extends javax.swing.JFrame {

    /**
     * Creates new form Converter
     */
    public Converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_to = new javax.swing.JLabel();
        jLabel_from = new javax.swing.JLabel();
        jTextField_amount = new javax.swing.JTextField();
        jComboBox_fromunit = new javax.swing.JComboBox<>();
        jComboBox_to = new javax.swing.JComboBox<>();
        jButton_convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CURRENCY CONVERTER");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Amount to convert");

        jLabel_to.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_to.setText("To");

        jLabel_from.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        jLabel_from.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_from.setText("FROM");

        jTextField_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_amountActionPerformed(evt);
            }
        });

        jComboBox_fromunit.setFont(new java.awt.Font("Vrinda", 0, 15)); // NOI18N
        jComboBox_fromunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "Indian Rupee", "Pound" }));

        jComboBox_to.setFont(new java.awt.Font("Vrinda", 0, 15)); // NOI18N
        jComboBox_to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rupee", "Chinese Yuan", "Canadian Dollar", "Euro", "USD" }));

        jButton_convert.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jButton_convert.setText("CONVERT");
        jButton_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_convertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_from, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_to, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_fromunit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_to, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_amount))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_convert, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_from, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_fromunit))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_to, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_to))
                .addGap(44, 44, 44)
                .addComponent(jButton_convert, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_amountActionPerformed

    private void jButton_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_convertActionPerformed
        // TODO add your handling code here:
        
        Double rate;
        
        Double amount = Double.parseDouble(jTextField_amount.getText());
        
        if(jComboBox_fromunit.getSelectedItem().toString() == "USD" )
        {
            if(jComboBox_to.getSelectedItem().toString() == "Indian Rupee")
            {
                rate = amount * 82.33;
                JOptionPane.showMessageDialog(this, "Your amount will be ₹" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Chinese Yuan"){
                rate = amount * 6.89;
                JOptionPane.showMessageDialog(this, "Your amount will be ¥‎" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Canadian Dollar"){
                rate = amount * 1.36;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Euro"){
                rate = amount * 0.92;
                JOptionPane.showMessageDialog(this, "Your amount will be €" + rate.toString());
            }
            else {
                rate = amount;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
        }
        
        else if(jComboBox_fromunit.getSelectedItem().toString() == "Indian Rupee" ){
            
            if(jComboBox_to.getSelectedItem().toString() == "USD")
            {
                rate = amount * 0.012;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Chinese Yuan"){
                rate = amount * 0.084;
                JOptionPane.showMessageDialog(this, "Your amount will be ¥‎" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Canadian Dollar"){
                rate = amount * 0.084;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Euro"){
                rate = amount * 0.011;
                JOptionPane.showMessageDialog(this, "Your amount will be €" + rate.toString());
            }
            else {
                rate = amount;
                JOptionPane.showMessageDialog(this, "Your amount will be ₹" + rate.toString());
            }
        }
        
        else{
            
            if(jComboBox_to.getSelectedItem().toString() == "USD")
            {
                rate = amount * 1.23;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Chinese Yuan"){
                rate = amount * 8.49;
                JOptionPane.showMessageDialog(this, "Your amount will be ¥‎" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Canadian Dollar"){
                rate = amount * 1.68;
                JOptionPane.showMessageDialog(this, "Your amount will be $" + rate.toString());
            }
            else if(jComboBox_to.getSelectedItem().toString() == "Euro"){
                rate = amount * 1.14;
                JOptionPane.showMessageDialog(this, "Your amount will be €" + rate.toString());
            }
            else {
                rate = amount * 101.47;
                JOptionPane.showMessageDialog(this, "Your amount will be ₹" + rate.toString());
        
        }
    }//GEN-LAST:event_jButton_convertActionPerformed
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_convert;
    private javax.swing.JComboBox<String> jComboBox_fromunit;
    private javax.swing.JComboBox<String> jComboBox_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_from;
    private javax.swing.JLabel jLabel_to;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_amount;
    // End of variables declaration//GEN-END:variables
}
